# Generated by Django 4.1.4 on 2022-12-10 10:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import game_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя автора')),
                ('age', models.IntegerField(verbose_name='Возраст автора')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Страна/Родина автора')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='game_site_django/author_poster', verbose_name='Постер автора')),
                ('url', models.SlugField(blank=True, null=True, verbose_name='Ссылка на автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название жанра')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание жанра')),
                ('url', models.SlugField(blank=True, null=True, verbose_name='Ссылка на жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название студии')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='game_site_django/game_poster', verbose_name='Постер студии')),
                ('url', models.SlugField(blank=True, null=True, verbose_name='Ссылка на студию')),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cpu', models.CharField(max_length=30, verbose_name='Название CPU')),
                ('name_gpu', models.CharField(max_length=30, verbose_name='Название GPU')),
                ('amount_type_memory', models.CharField(max_length=30, verbose_name='Объем и тип ОЗУ')),
                ('os', models.CharField(max_length=30, verbose_name='Название ОС')),
            ],
            options={
                'verbose_name': 'Системные требования к игре',
                'verbose_name_plural': 'Системные требования к игре',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название игры')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание игры')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='game_site_django/game_poster', verbose_name='Постер игры')),
                ('date_add_game', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления книги на сайт')),
                ('date_release', models.DateField(blank=True, null=True, validators=[game_app.models.check_game_date_release], verbose_name='Дата выхода игры')),
                ('price', models.IntegerField(verbose_name='Цена игры')),
                ('like', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Minimum value for like is 0.')], verbose_name='Like игры')),
                ('draft', models.BooleanField(default=False, verbose_name='Релиз игры')),
                ('url', models.SlugField(blank=True, null=True, verbose_name='Ссылка на игру')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game_app.author')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game_app.genre')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game_app.studio')),
                ('system_requirements', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_app.systemrequirements')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['name'],
            },
        ),
    ]
